#!/usr/bin/env python3
# Name: Sahasra Shankar (sshanka8)
# Group Members: Shweta Jones and Pranav Muthuraman (shsujones and pmuthura)
  #BME Final Code- Tabula Muris (UCSC GENOMICS)
  import csv
class fileFields():
    organName = ''
    ontologyName = ''

class filterTabula:
    def __init__(self, filename):
        self.inputFile = filename

    def splitToFiles(self):
        pass

    def sortCellOnt(self):
        pass

    def sortMouseId(self):
        pass

    def fileParser(self, readFile):
        # FileReader
         for column in self.inputFile:
            record = readFile
            recordObj = new fileFields()
             organ_name = record.getColumnOrgan()
             ontologyName = record.getOntologyName()
             pushToList(record, organName, ontologyName)
        #     recordObj =
        # writeFiles()

    def pushToList(self, rec, organNm, ontologyNm):
        pass

    def writeFiles(self):
        fileNameToWrite = ('meta_{:s}.txt'.format(organName.lower())
        #fw = open_the_file_write
        #fw.write(rec)

def main():
    tsv_file = open("meta.tsv")
    read_tsv = csv.reader(tsv_file, delimiter="\t")
    filtered_TM = filterTabula (tsv_file)
    #tsv_file.writeFiles()

if __name__ == "__main__":
    main()
